config/routes.rb
Rails.application.routes.draw do  
  resources :dishes
  root to: 'restaurants#index'
  # devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  resources :users do 
    collection do
      get :settings
      post :upload_logo
    end
  end


  # resources :dishes do 
  #   collection do 
  #     get :add_from_sample
  #   end 
  # end

  resources :webhooks, :none do
    collection do
      post :sync_mealhistory
    end
  end

  resources :restaurants do
    collection do
      get :sync
    end
    resources :dishes do
      get :add_from_sample      
    end
  end

  resources :analytics do
  	collection do
      get :dish_frequency
      post :dish_frequency
      get :frequent_users
      post :send_push
      get :user_frequency
      post :user_frequency
      get '/frequent_dishes/:rest_id' => 'analytics#frequent_dishes', as: :frequent_dishes
      post '/frequent_dishes/:rest_id' => 'analytics#frequent_dishes'
  	end
  end

end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  before_action :authenticate_user!

  def index    
    @history = MealHistory.history current_user.parse_merchant_id

    frequency = Hash.new
    
    @history.each do |h|
      hour = h["createdAt"].to_datetime.hour
      
      if frequency.has_key? hour
        frequency[hour] = frequency[hour].to_i + 1
      else
        frequency[hour] = 1
      end      
    end
    gon.y_axis = frequency.values.sort
    gon.x_axis = frequency.keys.sort.map { |e| "%02d" % e + ":00" }

  end

  def user_frequency
    @start_date = params[:start_date].present? ? params[:start_date] : (Date.today-7.days).strftime('%d/%m/%Y')
    @end_date = params[:end_date].present? ? params[:end_date] : (Date.today).strftime('%d/%m/%Y')

    @history = MealHistory.history current_user.parse_merchant_id,@start_date.to_datetime,@end_date.to_datetime

    frequency = Hash.new

    @history.each do |h|
      #hour = h["createdAt"].to_datetime.hour
      hour = h.parse_created_date.day
      if frequency.has_key? hour
        frequency[hour] = frequency[hour].to_i + 1
      else
        frequency[hour] = 1
      end
    end
    gon.y_axis = frequency.values.sort
    gon.x_axis = frequency.keys.sort #.map { |e| "%02d" % e + ":00" }
  end

  def frequent_dishes
    system "rake parse:cafedb"
    ####################################################
    @start_date = params[:start_date].present? ? params[:start_date] : (Date.today-7.days).strftime('%d/%m/%Y')
    @end_date = params[:end_date].present? ? params[:end_date] : (Date.today).strftime('%d/%m/%Y')
    ## Restaurant id is mandatory
    redirect_to restaurants_path(), notice: "Please provide a valid restaurant id." if params[:rest_id].blank?
    ####################################################

    parent_restaurant = Restaurant.where(objectId: params[:rest_id])
    
    Distance.where(parent_id: parent_restaurant.first.id).delete_all
    
    Restaurant.all.each do |r|
      dist = Restaurant.distance(parent_restaurant.first.lat.to_s + "," + parent_restaurant.first.lon.to_s, r.lat.to_s + "," + r.lon.to_s)
      puts "================= Calculated distance"
      puts dist

      if dist < 0.10  ## Only if distance is less than 100 meters
        Distance.create(parent_id: parent_restaurant.first.id, child_id: r.id, dist: dist, child_objectId: r.objectId)
      end
    end

    restaurants_in_radius = Distance.where(parent_id: parent_restaurant.first.id).order("dist desc").map &:child_objectId
    frequent_dishes_in_radius = MealHistory.where("cafedb_id IN(?) and (parse_created_date between ? and ?)", restaurants_in_radius,@start_date.to_datetime.beginning_of_day,@end_date.to_datetime.end_of_day).group(:dish_id).order("count_dish_id").limit(10).count("dish_id")
    
    dish = Parse::Query.new("mealsdummyx")
    dish.value_in('objectId', frequent_dishes_in_radius.map{|d| d[0]})
    @dishes = dish.get

    
    ds = {}
    @dishes.each do |d|
      ds[d["dish"]] = frequent_dishes_in_radius[d["objectId"]]
    end

    gon.y_axis = ds.values
    gon.x_axis = ds.keys
  end

  def dish_frequency
    @start_date = params[:start_date].present? ? params[:start_date] : (Date.today-7.days).strftime('%d/%m/%Y')
    @end_date = params[:end_date].present? ? params[:end_date] : (Date.today).strftime('%d/%m/%Y')
    @frequency = MealHistory.dishes_frequency current_user.parse_merchant_id,@start_date.to_datetime,@end_date.to_datetime
    
    gon.y_axis = @frequency.values
    gon.x_axis = @frequency.keys
  end

  def frequent_users
    @f_users = MealHistory.frequent_users    

  end

  def send_push
    msg = { :push_type => 'Message',
      :aps => { 
        :alert => params[:send_push][:message],
        :sound => "default"
      }
    }
    

    pointers = []
    params[:users].each do |p|
      pointers << Parse::Pointer.new({"className" => "_User", "objectId" => p})
    end

    query = Parse::Query.new(Parse::Protocol::CLASS_INSTALLATION).value_in('user_id', pointers)
    push = Parse::Push.new(msg)
    push.where = query.where
    push.save

    redirect_to frequent_users_analytics_path(), notice: "Push notifications sent to selected users."
  end

end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/views/analytics/dish_frequency.slim
.hpanel
  .panel-body
    .row
      .pull-left
        h2.font-light.m-b-xs
          | Analytics
      .pull-right
        = simple_form_for :dish_frequency,url: dish_frequency_analytics_path do |f|
          .pull-left.m-r.xs
            input.form-control.datepicker type='text' placeholder='Start Date' name='start_date' data-provide="datepicker" data-date-format="dd/mm/yyyy" value="#{@start_date}"
          .pull-left.m-r.xs
            input.form-control.datepicker type='text' placeholder='End Date' name='end_date' data-provide="datepicker" data-date-format="dd/mm/yyyy" value="#{@end_date}"
          .pull-right.m-r.xs
            input.btn.btn-small type='submit' value='Go'

.row
    .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
      .hpanel     
        .panel-body        
          - if @frequency.empty?
            .text-info
              | Currently no stats are available.
          - else
            div
            	canvas#lineOptions height="240"

          .text-center
            h1.m-xs.font-trans Dish Frequency

javascript:
	$(function () {
    /**
     * Options for Line chart
     */
    var lineData = {
        labels: gon.x_axis,
        datasets: [
            
            {
                label: "Example dataset",
                fillColor: "rgba(98,203,49,0.5)",
                strokeColor: "rgba(98,203,49,0.7)",
                pointColor: "rgba(98,203,49,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(26,179,148,1)",
                data: gon.y_axis
            }
        ]
    };

    var lineOptions = {
        scaleShowGridLines : true,
        scaleGridLineColor : "rgba(0,0,0,.05)",
        scaleGridLineWidth : 1,
        bezierCurve : true,
        bezierCurveTension : 0.4,
        pointDot : true,
        pointDotRadius : 4,
        pointDotStrokeWidth : 1,
        pointHitDetectionRadius : 20,
        datasetStroke : true,
        datasetStrokeWidth : 1,
        datasetFill : true,
        responsive: true
    };


    var ctx = document.getElementById("lineOptions").getContext("2d");
    var myNewChart = new Chart(ctx).Line(lineData, lineOptions);

        
    });

app/views/analytics/frequent_dishes.slim
.hpanel
  .panel-body      
    .row
      .pull-left
        h2.font-light.m-b-xs
          | Zone Stats
      .pull-right
        = simple_form_for :frequent_dishes,url: frequent_dishes_analytics_path(rest_id: params[:rest_id]) do |f|
          .pull-left.m-r.xs
            input.form-control.datepicker type='text' placeholder='Start Date' name='start_date' data-provide="datepicker" data-date-format="dd/mm/yyyy" value="#{@start_date}"
          .pull-left.m-r.xs
            input.form-control.datepicker type='text' placeholder='End Date' name='end_date' data-provide="datepicker" data-date-format="dd/mm/yyyy" value="#{@end_date}"
          .pull-right.m-r.xs
            input.btn.btn-small type='submit' value='Go'

.row
  .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
    .hpanel     
      .panel-body
        - if @dishes.any?
          div
            canvas#lineOptions height="240"

          .text-center
            h1.m-xs.font-trans Frequent Dishes

        - else
          .alert.alert-danger Currently no popular dish found around your restarurant.

javascript:
  $(function () {
    /**
     * Options for Line chart
     */
    var lineData = {
        labels: gon.x_axis,
        datasets: [
            
            {
                label: "Example dataset",
                fillColor: "rgba(98,203,49,0.5)",
                strokeColor: "rgba(98,203,49,0.7)",
                pointColor: "rgba(98,203,49,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(26,179,148,1)",
                data: gon.y_axis
            }
        ]
    };

    var lineOptions = {
        scaleShowGridLines : true,
        scaleGridLineColor : "rgba(0,0,0,.05)",
        scaleGridLineWidth : 1,
        bezierCurve : true,
        bezierCurveTension : 0.4,
        pointDot : true,
        pointDotRadius : 4,
        pointDotStrokeWidth : 1,
        pointHitDetectionRadius : 20,
        datasetStroke : true,
        datasetStrokeWidth : 1,
        datasetFill : true,
        responsive: true
    };


    var ctx = document.getElementById("lineOptions").getContext("2d");
    var myNewChart = new Chart(ctx).Line(lineData, lineOptions);

        
    });

app/views/analytics/frequent_users.slim
.hpanel
  .panel-body      
    #hbreadcrumb.pull-right.m-t-lg      
        

    h2.font-light.m-b-xs
      | Frequent Users

.row
  .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
    .hpanel     
      .panel-body
        = simple_form_for :send_push, url: send_push_analytics_path() do |f|
          .row
            .col-md-8
              table.table.table-bordered.table-striped
                thead
                  tr
                    th 
                    th ID
                    th Count

                tbody
                  - @f_users.each do |u|
                    tr
                      / td = f.input "push_user[]", as: :boolean, label: false, input_html: { checked: u["objectId"] }
                      td = check_box_tag "users[]", u.first, false
                      td = u.first
                      td = u.second

            .col-md-4
              label Message box
              br
              = f.input :message, as: :text, label: false
              br
              = f.submit "Send Push", class: "btn btn-success"

app/views/analytics/index.slim
.hpanel
  .panel-body      
    #hbreadcrumb.pull-right.m-t-lg      
        

    h2.font-light.m-b-xs
      | Analytics

.row
    .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
      .hpanel     
        .panel-body        
          - if @history.empty?
            .text-info
              | Currently no stats are available.
          - else
            div
            	canvas#lineOptions height="140"

          .text-center
            h1.m-xs.font-trans User Frequency

javascript:
	$(function () {


        /**
         * Options for Line chart
         */
        var lineData = {
            labels: gon.x_axis,
            datasets: [
                
                {
                    label: "Example dataset",
                    fillColor: "rgba(98,203,49,0.5)",
                    strokeColor: "rgba(98,203,49,0.7)",
                    pointColor: "rgba(98,203,49,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(26,179,148,1)",
                    data: gon.y_axis
                }
            ]
        };

        var lineOptions = {
            scaleShowGridLines : true,
            scaleGridLineColor : "rgba(0,0,0,.05)",
            scaleGridLineWidth : 1,
            bezierCurve : true,
            bezierCurveTension : 0.4,
            pointDot : true,
            pointDotRadius : 4,
            pointDotStrokeWidth : 1,
            pointHitDetectionRadius : 20,
            datasetStroke : true,
            datasetStrokeWidth : 1,
            datasetFill : true,
            responsive: true
        };


        var ctx = document.getElementById("lineOptions").getContext("2d");
        var myNewChart = new Chart(ctx).Line(lineData, lineOptions);

        
    });

app/views/analytics/user_frequency.slim
.hpanel
  .panel-body      
    .row
      .pull-left
        h2.font-light.m-b-xs
          | User Frequency
      .pull-right
        = simple_form_for :user_frequency,url: user_frequency_analytics_path do |f|
          .pull-left.m-r.xs
            input.form-control.datepicker type='text' placeholder='Start Date' name='start_date' data-provide="datepicker" data-date-format="dd/mm/yyyy" value="#{@start_date}"
          .pull-left.m-r.xs
            input.form-control.datepicker type='text' placeholder='End Date' name='end_date' data-provide="datepicker" data-date-format="dd/mm/yyyy" value="#{@end_date}"
          .pull-right.m-r.xs
            input.btn.btn-small type='submit' value='Go'


.row
    .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
      .hpanel     
        .panel-body        
          - if @history.empty?
            .text-info
              | Currently no stats are available.
          - else
            div
            	canvas#lineOptions height="140"

          .text-center
            h1.m-xs.font-trans User Frequency

javascript:
	$(function () {


        /**
         * Options for Line chart
         */
        var lineData = {
            labels: gon.x_axis,
            datasets: [
                
                {
                    label: "Example dataset",
                    fillColor: "rgba(98,203,49,0.5)",
                    strokeColor: "rgba(98,203,49,0.7)",
                    pointColor: "rgba(98,203,49,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(26,179,148,1)",
                    data: gon.y_axis
                }
            ]
        };

        var lineOptions = {
            scaleShowGridLines : true,
            scaleGridLineColor : "rgba(0,0,0,.05)",
            scaleGridLineWidth : 1,
            bezierCurve : true,
            bezierCurveTension : 0.4,
            pointDot : true,
            pointDotRadius : 4,
            pointDotStrokeWidth : 1,
            pointHitDetectionRadius : 20,
            datasetStroke : true,
            datasetStrokeWidth : 1,
            datasetFill : true,
            responsive: true
        };


        var ctx = document.getElementById("lineOptions").getContext("2d");
        var myNewChart = new Chart(ctx).Line(lineData, lineOptions);

        
    });