config/routes.rb
Rails.application.routes.draw do  
  resources :dishes
  root to: 'restaurants#index'
  # devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  resources :users do 
    collection do
      get :settings
      post :upload_logo
    end
  end


  # resources :dishes do 
  #   collection do 
  #     get :add_from_sample
  #   end 
  # end

  resources :webhooks, :none do
    collection do
      post :sync_mealhistory
    end
  end

  resources :restaurants do
    collection do
      get :sync
    end
    resources :dishes do
      get :add_from_sample      
    end
  end

  resources :analytics do
  	collection do
      get :dish_frequency
      post :dish_frequency
      get :frequent_users
      post :send_push
      get :user_frequency
      post :user_frequency
      get '/frequent_dishes/:rest_id' => 'analytics#frequent_dishes', as: :frequent_dishes
      post '/frequent_dishes/:rest_id' => 'analytics#frequent_dishes'
  	end
  end

end

app/models/dish.rb
class Dish < ActiveRecord::Base
	DISHES_CLASS_NAME = "mealsdummyx"
  RESTAURANT_CLASS_NAME = "cafedb"

	def self.create_dish dish_attributes
    pointer = Parse::Pointer.new({"className" => RESTAURANT_CLASS_NAME, "objectId" => dish_attributes["cafedb_id"]})

		dish = Parse::Object.new(DISHES_CLASS_NAME)
		dish["dish"] = dish_attributes["name"]
		dish["price"] = dish_attributes["price"].to_i
		dish["cafedb_id"] = pointer
    dish["description"] = dish_attributes["description"]
    dish["imgurl"] = dish_attributes["imgurl"]

		dish.save
	end

  def self.create_from_sample sample_dish, parse_restaurant_id    
    dish = Parse::Object.new(DISHES_CLASS_NAME)
    pointer = Parse::Pointer.new({"className" => RESTAURANT_CLASS_NAME, "objectId" => parse_restaurant_id})
    sample_dish.each do |key, value|
      dish[key] = value unless key.eql? "objectId"
    end
    dish["cafedb_id"] = pointer
    
    dish.save
  end

  def self.get_dish objectId
    dish = Parse::Query.new(DISHES_CLASS_NAME)
    dish.eq("objectId", objectId)
    dish.get.first
  end

  def self.get_dishes objects
    dish = Parse::Query.new(DISHES_CLASS_NAME)    
    dish.value_in("objectId", objects)
    dish.get
  end  

  def self.delete_dish objectId
    dish = Parse::Query.new(DISHES_CLASS_NAME)
    dish.eq("objectId", objectId)
    dish.get.first.parse_delete
  end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :authenticate_user!

  def new
    @rst = Restaurant.get_restaurant params[:restaurant_id]
    @sample_dishes = SampleDish.get_dishes
  end

  def show
    @dish = Dish.get_dish params[:id]
  end

  def edit
    @dish = Dish.get_dish params[:id]
  end

  def create
    uploader = DishImageUploader.new
    a = uploader.store!(params["dish_image"])    

    dish_attributes = params["dish"]
    dish_attributes["imgurl"] = uploader.url
    Dish.create_dish dish_attributes

    redirect_to restaurant_path(id: dish_attributes["cafedb_id"]), notice: "Dish has been added successfully."
  end

  def update
    @dish = Dish.get_dish params[:id]
    dish = params["dish"]
    @dish["dish"] = dish["name"]
    @dish["price"] = dish["price"].to_f
    @dish["description"] = dish["description"]

    if params[:dish_image].present?
      uploader = DishImageUploader.new
      uploader.store!(params["dish_image"])
      @dish["imgurl"] = uploader.url
    end

    result = @dish.save
    puts result
    redirect_to restaurant_dish_path(id: params["id"],restaurant_id: dish["cafedb_id"]), notice: "Dish has been updated successfully."
  end

  def destroy
    begin
      Dish.delete_dish(params[:id])
    rescue Exception => e
      puts "## ============ Exception =========== ##"
      puts e.message
    end

    redirect_to restaurant_path(id: params["restaurant_id"]), notice: "Dish has been deleted successfully."
  end

  def add_from_sample
    @dish = SampleDish.get_dish(params[:dish_id])
    
    dish = Dish.create_from_sample(@dish, params[:restaurant_id])
    
    redirect_to dish_path(id: dish["objectId"]), notice: "Dish copied to your restaurant successfully."
  end

end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.slim
= simple_form_for :dish, url: "/dishes", html: { class: "dishes_form", multipart: true } do |f|
  .form-inputs
    = f.input :name, label: false, placeholder: "Dish name", class: 'form-control'

  .form-inputs
    = f.input :price, label: false, placeholder: "Price", class: 'form-control'
    = f.input :cafedb_id, as: "hidden", input_html: { value: params[:restaurant_id] }

  .form-inputs
    = f.input :description, label: false, as: :text, placeholder: "Enter description here...", class: 'form-control'

  .form-inputs
    = file_field_tag :dish_image
  
  br
  .form-actions
    = f.submit "Add", class: "btn btn-primary btn-add-dish"
    |  
    = link_to 'Back', restaurant_path(id: @rst["objectId"]), class: "btn btn-default"

app/views/dishes/_form_edit.slim
= simple_form_for :dish, url: "/dishes/#{@dish['objectId']}", html: { class: "dishes_form", multipart: true }, method: :update do |f|
  .form-inputs
    = f.input :name, label: false, placeholder: "Dish name", class: 'form-control', input_html: { value: @dish["dish"] }
    = f.input :cafedb_id, as: "hidden", input_html: { value: params[:restaurant_id] }

  .form-inputs
    = f.input :price, label: false, placeholder: "Price", class: 'form-control', input_html: { value: @dish["price"] }

  .form-inputs
    = f.input :description, label: false, as: :text, placeholder: "Enter description here...", class: 'form-control', input_html: { value: @dish["description"] }
    
    <input name="_method" type="hidden" value="patch" />

  .form-inputs
    = image_tag @dish["imgurl"], size: "200x200"

  .form-inputs
    = file_field_tag :dish_image

  br
  .form-actions
    = f.submit "Update", class: "btn btn-primary btn-add-dish"
    |  
    = link_to 'Back', restaurant_path(id: params[:restaurant_id]), class: "btn btn-default"

app/views/dishes/_sample_dishes.slim
.content.animate-panel
  - dishes.each_slice(3) do |quad_dishes|
    .row
      - quad_dishes.each do |dish|
        .col-lg-4 style="" 
          .hpanel.hgreen.contact-panel
            .panel-body
              = link_to restaurant_dish_add_from_sample_path(restaurant_id: params[:restaurant_id], dish_id: dish["objectId"]) do
                span.label.label-success.pull-right
                  i.fa.fa-plus

              = image_tag "default_dish.jpg", class: "img-circle m-b", alt: "logo"
              h3
                a href=""
                  = dish["dish"]
              p
                = dish["description"]
            .panel-footer.contact-footer
              .row
                .col-md-4.border-right style="" 
                  .contact-stat
                    span Proteins
                    strong = dish["prot_percent"]
                .col-md-4.border-right style="" 
                  .contact-stat
                    span Fat
                    strong = dish["fatgms"]
                .col-md-4 style="" 
                  .contact-stat
                    span Energy
                    strong = dish["energyKcal"]
      
      / .col-lg-3 style="" 
      /   .hpanel.hyellow.contact-panel
      /     .panel-body
      /       = image_tag "default_dish.jpg", class: "img-circle m-b", alt: "logo"
      /       h3
      /         a href=""  Tangela Sternberg
      /       .text-muted.font-bold.m-b-xs California, LA
      /       p
      /         | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
      /     .panel-footer.contact-footer
      /       .row
      /         .col-md-4.border-right style="" 
      /           .contact-stat
      /             span Projects:
      /             strong 200
      /         .col-md-4.border-right style="" 
      /           .contact-stat
      /             span Messages:
      /             strong 300
      /         .col-md-4 style="" 
      /           .contact-stat
      /             span Views:
      /             strong 400
      / .col-lg-3 style="" 
      /   .hpanel.hviolet.contact-panel
      /     .panel-body
      /       img.img-circle.m-b alt="logo" src="images/a2.jpg" /
      /       h3
      /         a href=""  Claud Vogan
      /       .text-muted.font-bold.m-b-xs California, LA
      /       p
      /         | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
      /     .panel-footer.contact-footer
      /       .row
      /         .col-md-4.border-right style="" 
      /           .contact-stat
      /             span Projects:
      /             strong 200
      /         .col-md-4.border-right style="" 
      /           .contact-stat
      /             span Messages:
      /             strong 300
      /         .col-md-4 style="" 
      /           .contact-stat
      /             span Views:
      /             strong 400
      / .col-lg-3 style="" 
      /   .hpanel.hblue.contact-panel
      /     .panel-body
      /       img.img-circle.m-b alt="logo" src="images/a3.jpg" /
      /       h3
      /         a href=""  Valda Purdy
      /       .text-muted.font-bold.m-b-xs California, LA
      /       p
      /         | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
      /     .panel-footer.contact-footer
      /       .row
      /         .col-md-4.border-right style="" 
      /           .contact-stat
      /             span Projects:
      /             strong 200
      /         .col-md-4.border-right style="" 
      /           .contact-stat
      /             span Messages:
      /             strong 300
      /         .col-md-4 style="" 
      /           .contact-stat
      /             span Views:
      /             strong 400
  
  

app/views/dishes/edit.slim
.hpanel
  .panel-body    
    h2.font-light.m-b-xs
      | Edit
    

.row
  .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
    .hpanel     
      .panel-body
        == render 'form_edit'

app/views/dishes/new.slim
.hpanel
  .panel-body    
    h2.font-light.m-b-xs
      | Add a Dish to #{@rst["cafename"]}
    
.row
  .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
    .hpanel     
      .panel-body
        h3 Choose from our Sample Dishes
        = render partial: "sample_dishes", locals: { dishes: @sample_dishes }
.row
  .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
    .hpanel     
      .panel-body
        h3 Or add your own
      	== render 'form'

app/views/dishes/show.slim
.hpanel
  .panel-body
    #hbreadcrumb.pull-right.m-t-lg
      ol.hbreadcrumb.breadcrumb
        li
          = link_to 'Back', restaurant_path(id: params[:restaurant_id]), class: "btn btn-primary btn-xs"
          |  
          = link_to "Edit", edit_restaurant_dish_path(id: @dish["objectId"],restaurant_id: params[:restaurant_id]), class: 'btn btn-primary btn-xs'

    h2.font-light.m-b-xs
      = @dish["dish"]
      

.row
  .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
    .hpanel     
      .panel-body
        strong Price: 
        = number_to_currency(@dish["price"])

        br
        br
        strong Description: 
        = @dish["description"]

        br
        br
        
        -if @dish["imgurl"] 
          = image_tag @dish["imgurl"] , size: "100x100"
        -else
          = image_tag "default_dish.jpg", class: "img-circle m-b", alt: "logo"