config/routes.rb
Rails.application.routes.draw do  
  resources :dishes
  root to: 'restaurants#index'
  # devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  resources :users do 
    collection do
      get :settings
      post :upload_logo
    end
  end


  # resources :dishes do 
  #   collection do 
  #     get :add_from_sample
  #   end 
  # end

  resources :webhooks, :none do
    collection do
      post :sync_mealhistory
    end
  end

  resources :restaurants do
    collection do
      get :sync
    end
    resources :dishes do
      get :add_from_sample      
    end
  end

  resources :analytics do
  	collection do
      get :dish_frequency
      post :dish_frequency
      get :frequent_users
      post :send_push
      get :user_frequency
      post :user_frequency
      get '/frequent_dishes/:rest_id' => 'analytics#frequent_dishes', as: :frequent_dishes
      post '/frequent_dishes/:rest_id' => 'analytics#frequent_dishes'
  	end
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

	RESTAURANT_CLASS_NAME = "cafedb"
	DISHES_CLASS_NAME = "mealsdummyx"

	def self.get_restaurant objectId
		restaurant = Parse::Query.new(RESTAURANT_CLASS_NAME)
    restaurant.eq("objectId", objectId)
    restaurant.get.first
	end

	def self.dishes restaurant_objectid

		dishes = Parse::Query.new(DISHES_CLASS_NAME)
	pointer = Parse::Pointer.new({"className" => RESTAURANT_CLASS_NAME, "objectId" => restaurant_objectid})
	dishes.eq("cafedb_id", pointer)
    dishes.get
	end

  def self.distance loc1str, loc2str
    loc1 = loc1str.split(',')
    loc2 = loc2str.split(',')

    loc1 = [loc1[0].to_f, loc1[1].to_f]
    loc2 = [loc2[0].to_f, loc2[1].to_f]
    
    rad_per_deg = Math::PI/180  # PI / 180
    # rmiles = 3959               # Earth Radius in miles
    rkm = 6371                # Earth radius in kilometers

    dlat_rad = (loc2[0]-loc1[0]) * rad_per_deg  # Delta, converted to rad
    dlon_rad = (loc2[1]-loc1[1]) * rad_per_deg

    lat1_rad, lon1_rad = loc1.map {|i| i * rad_per_deg }
    lat2_rad, lon2_rad = loc2.map {|i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))

    rkm * c # Delta in kms
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!

  PARSE_CLASS_NAME = "cafedb"

  include ParseApi

  def index
    @restaurants = get_restaurants current_user
  end

  def show
    @restaurant = Restaurant.get_restaurant params[:id]
    @dishes = Restaurant.dishes @restaurant["objectId"]
  end

  def edit
    @restaurant = Restaurant.get_restaurant params[:id]
  end

  def create
    create_restaurant params[:restaurant], current_user
    
    redirect_to restaurants_path, notice: "Your restaurant has been added successfully."
  end

  def update
    @restaurant = Restaurant.get_restaurant params[:id]
    restaurant = params["restaurant"]
    @restaurant["cafename"] = restaurant["cafename"]
    @restaurant["cafelocation"] = restaurant["cafelocation"]

    result = @restaurant.save
    puts result

    redirect_to restaurants_path(id: restaurant["id"])
  end

  def sync
    system "rake parse:mealhistory"
    redirect_to restaurants_path, notice: "Syncing completed."
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.slim
= simple_form_for :restaurant, :url => "/restaurants", html: {class: "restaurant_form"} do |f|

  .form-inputs
    = f.input :cafename, label: false, placeholder: "Restaurant Name", class: 'form-control'

  .form-inputs
    = f.input :cafelocation, label: false, placeholder: "Address", class: 'form-control'

  .form-inputs
    = f.input :zipcode, label: false, placeholder: "ZipCode", class: 'form-control'

  br
  .form-actions
    = f.submit "Add", class: "btn btn-primary"
    |  
    = link_to 'Back', restaurants_path, class: "btn btn-default"

app/views/restaurants/_form_edit.slim
= simple_form_for :restaurant, :url => "/restaurants/#{@restaurant['objectId']}", method: :update do |f|

  .form-inputs
    = f.input :cafename, label: false, placeholder: "Restaurant Name", class: 'form-control', input_html: { value: @restaurant["cafename"] }

  .form-inputs
    = f.input :cafelocation, label: false, placeholder: "Address", class: 'form-control', input_html: { value: @restaurant["cafelocation"] }
    input name="_method" type="hidden" value="patch"

  br
  .form-actions
    = f.submit "Update", class: "btn btn-primary"
    |  
    = link_to 'Back', restaurant_path(id: @restaurant["objectId"]), class: "btn btn-default"

app/views/restaurants/edit.slim
.hpanel
  .panel-body    
    h2.font-light.m-b-xs
      | Edit Restaurant

.row
  .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
    .hpanel     
      .panel-body
        == render 'form_edit'

app/views/restaurants/index.slim
.hpanel
  .panel-body      
    #hbreadcrumb.pull-right.m-t-lg
      ol.hbreadcrumb.breadcrumb
        li          
          = link_to 'Add a Restaurant', new_restaurant_path, class: "btn btn-primary btn-xs"
          |  
          = link_to 'Sync', sync_restaurants_path, class: "btn btn-primary btn-xs"
        

    h2.font-light.m-b-xs
      | My Restaurants
    small Listing Restaurants


- if current_user.parse_merchant_id.blank?
  .alert.alert-info Currently not registered as a valid restaurant owner.
- else
  .row
    .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
      .hpanel     
        .panel-body        
          table.table cellpadding="1" cellspacing="1"
            thead
              tr
                th Restaurant Name
                th Location
                th Actions

            - @restaurants.each do |restaurant|
              tr
                td #{restaurant["cafename"]}
                td #{restaurant["cafelocation"]}
                td
                  = link_to "Add Dishes", new_restaurant_dish_path(restaurant_id: restaurant["objectId"]), class: 'btn btn-primary btn-xs'
                  |  
                  = link_to "Detail", restaurant_path(id: restaurant['objectId']), class: 'btn btn-primary btn-xs'
                  |  
                  = link_to frequent_dishes_analytics_path(rest_id: restaurant['objectId']), class: "btn btn-primary btn-xs" do
                    span.glyphicon.glyphicon-fire aria-hidden="true"
                  

app/views/restaurants/new.slim
.hpanel
  .panel-body    
    h2.font-light.m-b-xs
      | Add Restaurant
    

.row
  .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
    .hpanel     
      .panel-body
      	== render 'form'

app/views/restaurants/show.slim
.hpanel
  .panel-body
    #hbreadcrumb.pull-right.m-t-lg
      ol.hbreadcrumb.breadcrumb
        li          
          = link_to 'Edit', edit_restaurant_path(id: @restaurant["objectId"]), class: "btn btn-primary btn-xs"
          |  
          = link_to 'Add a Dish', new_restaurant_dish_path(restaurant_id: @restaurant["objectId"]), class: "btn btn-primary btn-xs"

    h2.font-light.m-b-xs
      = @restaurant["cafename"]
    small = @restaurant["cafelocation"]
    

.row
  .col-lg-12.animated-panel.zoomIn style=("-webkit-animation-delay: 0.2s;") 
    .hpanel     
      .panel-body
        h2 Dishes

        table.table
          thead
            tr
              th Name
              th Price
              th 
              th Actions


          tbody
            - @dishes.each do |d|
              tr
                td = d["dish"]
                td = number_to_currency(d["price"])
                td  
                  -if d["imgurl"] 
                    = image_tag d["imgurl"], size: "50x50"
                  -else
                    = image_tag "default_dish.jpg", class: "img-circle m-b", alt: "logo" , size: "50x50"

                td 
                  = link_to "View", restaurant_dish_path(id: d["objectId"],restaurant_id: @restaurant["objectId"]), class: 'btn btn-primary btn-xs'
                  |  
                  = link_to "Edit", edit_restaurant_dish_path(id: d["objectId"],restaurant_id: @restaurant["objectId"]), class: 'btn btn-primary btn-xs'
                  |  
                  = link_to "Delete", dish_path(id: d["objectId"], restaurant_id: @restaurant["objectId"]), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-primary btn-xs'