config/routes.rb
Rails.application.routes.draw do  
  resources :dishes
  root to: 'restaurants#index'
  # devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  resources :users do 
    collection do
      get :settings
      post :upload_logo
    end
  end


  # resources :dishes do 
  #   collection do 
  #     get :add_from_sample
  #   end 
  # end

  resources :webhooks, :none do
    collection do
      post :sync_mealhistory
    end
  end

  resources :restaurants do
    collection do
      get :sync
    end
    resources :dishes do
      get :add_from_sample      
    end
  end

  resources :analytics do
  	collection do
      get :dish_frequency
      post :dish_frequency
      get :frequent_users
      post :send_push
      get :user_frequency
      post :user_frequency
      get '/frequent_dishes/:rest_id' => 'analytics#frequent_dishes', as: :frequent_dishes
      post '/frequent_dishes/:rest_id' => 'analytics#frequent_dishes'
  	end
  end

end

app/views/layouts/_aside_navigation.slim
aside#menu
  #navigation
    .profile-picture
      a href="/"
        - if current_user.merchant_logo.blank?
          = image_tag "logo80x80.png", class: "img-circle m-b"
        - else
          = image_tag current_user.merchant_logo, class: "img-circle m-b"
      .stats-label.text-color
        - if user_signed_in?
          span.font-extra-bold #{current_user.email}
        .dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#" 
            small.text-muted
              | Foodingo Portal
              b.caret
          ul.dropdown-menu.animated.fadeInRight.m-t-xs
            li
              = link_to "#{current_user.merchant_logo.present? ? 'Update Logo' : 'Upload Logo'}", settings_users_path()
            
            li.divider
            li
              = link_to "Logout",destroy_user_session_path, :method=>'delete'
        #sparkline1.small-chart.m-t-sm
        div
          h4.font-extra-bold.m-b-xs
            | $260 104,200
          small.text-muted Your income from the last year in sales product X.
    

    ul#side-menu.nav
      li.active
        = link_to restaurants_path do
          span.nav-label My Restaurants
      li
        = link_to "#" do        
          span.nav-label My Analytics
          .fa.arrow

        ul.nav.nav-second-level.collapse
          li
            = link_to user_frequency_analytics_path do
              | User Frequency

          li
            = link_to dish_frequency_analytics_path do
              | Dish Popularity

          li
            = link_to frequent_users_analytics_path do
              | Frequent Users

      li
        = link_to "#" do
          span.nav-label My Market

app/views/layouts/_header.slim
#header
  .color-line
  #logo.light-version
    span
      | #{ current_user.present? ? current_user.name : 'Foodingo'}
  nav role="navigation" 
    .header-link.hide-menu
      i.fa.fa-bars
    .small-logo
      span.text-primary HOMER APP
    form.navbar-form-custom action="#" method="post" role="search" 
      .form-group
        input.form-control name="search" placeholder=("Search something special") type="text" /
    .navbar-right
      ul.nav.navbar-nav.no-borders
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#" 
            i.pe-7s-speaker
          ul.dropdown-menu.hdropdown.notification.animated.flipInX
            li
              a
                span.label.label-success NEW
                | It is a long established.
            li
              a
                span.label.label-warning WAR
                | There are many variations.
            li
              a
                span.label.label-danger ERR
                | Contrary to popular belief.
            li.summary
              a href="#"  See all notifications
        li.dropdown
          a.dropdown-toggle.label-menu-corner data-toggle="dropdown" href="#" 
            i.pe-7s-mail
            span.label.label-success 4
          ul.dropdown-menu.hdropdown.animated.flipInX
            .title
              | You have 4 new messages
            li
              a
                | It is a long established.
            li
              a
                | There are many variations.
            li
              a
                | Lorem Ipsum is simply dummy.
            li
              a
                | Contrary to popular belief.
            li.summary
              a href="#"  See All Messages

        li.dropdown
          = link_to destroy_user_session_path, :method=>'delete' do          
            i.pe-7s-upload.pe-rotate-90

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Categories', categories_path %></li>
  <li><%= link_to 'Menus', menus_path %></li>
  <li><%= link_to 'Device Table Mapping', device_table_mappings_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Foodingo Portal'}"
    title
      = content_for?(:title) ? yield(:title) : 'Foodingo Portal'
    = favicon_link_tag 'favicon.ico'
    /! Include style per-controller - vendor plugins
    = stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css")
    /! Main css styles
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    
    /! Main javascript files
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
        
    = csrf_meta_tags

    = include_gon

  body
    /! Simple splash screen
    .splash
      .color-line
      .splash-title
        h1 Homer - Responsive Admin Theme
        p Special AngularJS Admin Theme for small and medium webapp with very clean and aesthetic style and feel.    
        = image_tag "loading-bars.svg", width: "64", height: "64"

    /! Header
    = render 'layouts/header'

    /! Navigation
    = render 'layouts/aside_navigation'
    /! Main Wrapper

    #wrapper
      .content.animate-panel
        == render 'layouts/messages'
        == yield
    
    /! Include javascript per-controller - vendor plugins    
    = javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js")
    /! Include javascript per-view
    /! For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want
    = yield :javascript

app/views/layouts/empty.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Restaurant Menus'}"
    title
      = content_for?(:title) ? yield(:title) : 'Foodingo Portal'
    = favicon_link_tag 'favicon.ico'
    /! Include style per-controller - vendor plugins
    = stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css")
    /! Main css styles
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    
    /! Main javascript files
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
        
    = csrf_meta_tags

  body.blank
    /! Simple splash screen
    .splash
      .color-line
      .splash-title
        h1 Homer - Responsive Admin Theme
        p Special AngularJS Admin Theme for small and medium webapp with very clean and aesthetic style and feel.        
        = image_tag 'loading-bars.svg', :height => "64", :width => "64"
    
    .color-line
    == render 'layouts/messages'

    == yield
    
    /! Include javascript per-controller - vendor plugins    
    = javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js")
    /! Include javascript per-view
    /! For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want
    = yield :javascript